
package UI;

import control.MaintainLogin;
import domain.Login;
import javax.swing.JOptionPane;

public class ChangePassword extends javax.swing.JFrame {
    private MaintainLogin loginControl;

    /**
     * Creates new form ChangePassword
     */
    public ChangePassword() {
        loginControl = new MaintainLogin();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(550, 460));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CHANGE PASSWORD");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 30, 506, 52);
        jLabel2.getAccessibleContext().setAccessibleParent(this);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 255));
        jLabel3.setText(" USER NAME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 110, 162, 40);
        jLabel3.getAccessibleContext().setAccessibleParent(this);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 255));
        jLabel4.setText("OLD PASSWORD");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 170, 162, 46);
        jLabel4.getAccessibleContext().setAccessibleDescription("");
        jLabel4.getAccessibleContext().setAccessibleParent(this);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 255));
        jLabel5.setText("NEW PASSWORD");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 240, 162, 46);
        jLabel5.getAccessibleContext().setAccessibleParent(this);

        getContentPane().add(jTextField1);
        jTextField1.setBounds(260, 110, 179, 41);
        jTextField1.getAccessibleContext().setAccessibleParent(this);

        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(260, 180, 180, 40);
        jPasswordField1.getAccessibleContext().setAccessibleParent(this);

        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(260, 250, 180, 40);
        jPasswordField2.getAccessibleContext().setAccessibleParent(this);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(135, 349, 116, 37);
        jButton1.getAccessibleContext().setAccessibleParent(this);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(349, 349, 116, 37);
        jButton2.getAccessibleContext().setAccessibleParent(this);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 550, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Login login = loginControl.selectRecord(jTextField1.getText());

        String userid = String.valueOf(jTextField1.getText());
        String oldpass = String.valueOf(jPasswordField1.getText());
        String newpass = String.valueOf(jPasswordField2.getText());
        
        if(login == null){              
            JOptionPane.showMessageDialog(null, "No such user ID.", "RECORD NOT FOUND", JOptionPane.ERROR_MESSAGE);
        }
        else if(oldpass.equals("")||newpass.equals("")){
            JOptionPane.showMessageDialog(null, "Please key in your password.", "CHECK", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(oldpass.equals(newpass)){
            JOptionPane.showMessageDialog(null, "Same password. Please try again.", "Invalid information", JOptionPane.ERROR_MESSAGE);
        }
        else if(userid.equals(login.getUserid()) && oldpass.equals(login.getPassword())){
            login.setPassword(newpass);
            loginControl.updateRecord(login);
            JOptionPane.showMessageDialog(null,"Password has been change.","Update password", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            }
        else{
            JOptionPane.showMessageDialog(null, "Wrong password validation. Please try again", "invalid information", JOptionPane.ERROR_MESSAGE);
            jPasswordField1.setText(null);
            jPasswordField2.setText(null);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    public javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
